import { Analytics } from '@vercel/analytics/next'
import { inter } from '@/app/fonts'

import '@/styles/globals.css'

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Analytics />
				{children}
			</body>
		</html>
	)
}
